### ISSUE TITLE
OperationFailure: .... failed: exception: distinct too big, 16mb cap 

### ISSUE THREAD

**Issue by andrebco** [turicas/mongodict#10]
<pre>
In [1]: from mongodict import MongoDict

In [2]: data_dict = MongoDict(host='XXX.XXX.XXX.XXX', port=27017, database='XXXXX', collection='XXXXXX',safe=True)

In [4]: for i in data_dict.keys():
    raw_input()
    print i
   ...:     
---------------------------------------------------------------------------
OperationFailure                          Traceback (most recent call last)
<ipython-input-4-4aa8d30d290b> in <module>()
----> 1 for i in data_dict.keys():
      2     raw_input()
      3     print i
      4 

/usr/lib/python2.7/_abcoll.pyc in keys(self)
    364 
    365     def keys(self):
--> 366         return list(self)
    367 
    368     def items(self):

/home/xxxxx/.virtualenvs/xxxxxxx/lib/python2.7/site-packages/mongodict.pyc in __iter__(self)
     96     def __iter__(self):
     97         ''' Iterate over all stored keys '''
---> 98         for result in iter(self._collection.distinct('_id')):
     99             yield result
    100 

/home/xxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/pymongo/collection.pyc in distinct(self, key)
   1076         .. versionadded:: 1.1.1
   1077         """
-> 1078         return self.find().distinct(key)
   1079 
   1080     def map_reduce(self, map, reduce, out, full_response=False, **kwargs):

/home/xxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/pymongo/cursor.pyc in distinct(self, key)
    578                                 self.__collection.name,
    579                                 uuid_subtype = self.__uuid_subtype,
--> 580                                 **options)["values"]
    581 
    582     def explain(self):

/home/xxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/pymongo/database.pyc in command(self, command, value, check, allowable_errors, uuid_subtype, **kwargs)
    391             msg = "command %s failed: %%s" % repr(command).replace("%", "%%")
    392             helpers._check_command_response(result, self.connection.disconnect,
--> 393                                             msg, allowable_errors)
    394 
    395         return result

/home/xxxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/pymongo/helpers.pyc in _check_command_response(response, reset, msg, allowable_errors)
    142                                (details["assertionCode"],))
    143                 raise OperationFailure(ex_msg, details.get("assertionCode"))
--> 144             raise OperationFailure(msg % details["errmsg"])
    145 
    146 

OperationFailure: command SON([('distinct', u'dict_processos'), ('key', '_id')]) failed: exception: distinct too big, 16mb cap
</pre>

**Comment by turicas** [comment]
Nice catch! I need to implement a way to `mongodict` retrieve data based on this MongoDB limitation without raising any exceptions for mongodict's user.

The method that is affected by this bug is `__iter__`.
